services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    cpuset: "1,2"
    volumes:
      - "./experiments:/recordings/"
    deploy:
      resources:
        reservations:
          memory: 2000m
          cpus: 2.0
        limits:
          memory: 2000m
          cpus: 2.0
