apiVersion: apps/v1
kind: Deployment
metadata:
  name: ultimoguia
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ultimoguia:cds
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:ActiveProcessorCount=2"
          livenessProbe:
            httpGet:
              port: 8080
              path: "/actuator/health/liveness"
            initialDelaySeconds: 1
            failureThreshold: 3
            periodSeconds: 3
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              port: 8080
              path: "/actuator/health/readiness"
            initialDelaySeconds: 3
            failureThreshold: 3
            periodSeconds: 1
            timeoutSeconds: 1
          resources:
            requests:
              memory: "2000Mi"
              cpu: "2000m"
            limits:
              memory: "2000Mi"
              cpu: "2000m"
---
apiVersion: v1
kind: Service
metadata:
  name: ultimoguia-np
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
    - name: http-8081
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
